In [1]:
import numpy as np

In [3]:
my_list = [0,1,2,3,4]

arr = np.array(my_list)

print(arr)

[0 1 2 3 4]


In [4]:
type(arr)

numpy.ndarray

In [6]:
# Arange integers start, stop,step in Numpy
a = np.arange(1,50,4)
print(a)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [7]:
# Create an array of ones
a = np.ones((2,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Create an array of zeroes
a = np.zeros((2,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# Create a array of random integers

a = np.random.randint(0,10,(3,3))

print(a)

[[5 8 1]
 [5 9 1]
 [5 8 6]]


In [12]:
 #Create linearly spaced array
 a = np.linspace(0,10,5)
 
 print(a)

[ 0.   2.5  5.   7.5 10. ]


In [27]:
np.random.seed(100)

arr = np.random.randint(0,100,10)

print(arr)

[ 8 24 67 87 79 48 10 94 52 98]


In [28]:
np.random.seed(100)

arr2 = np.random.randint(0,100,10)

print(arr2)

[ 8 24 67 87 79 48 10 94 52 98]


In [29]:
print(arr2.max())

98


In [30]:
print(arr2.min())

8


In [31]:
print(arr2.mean())

56.7


In [33]:
print(round(arr2.std(),2))

32.15


In [44]:
np.random.seed(100)

a = np.random.randint(0,100,(3,4))

print(a)

print(a.argmin())

print(a.argmax())

print(a.reshape(4,3))


[[ 8 24 67 87]
 [79 48 10 94]
 [52 98 53 66]]
0
9
[[ 8 24 67]
 [87 79 48]
 [10 94 52]
 [98 53 66]]


In [46]:
# We can use .reshape() method to change the shape of a 1d arry to 2d, 3d and so on
np.random.seed(100)

mat = np.arange(0,100).reshape(10,10)

print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [47]:
row = 0
col = 1

In [48]:
print(mat[row,col])

1


In [49]:
print(mat[0,0])

0


In [50]:
print(mat[6,0])

60


In [51]:
# Masking
print(mat > 50)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [59]:
print(mat[(mat > 50) & (mat < 87)])

[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86]
